# Bouldering Spots - Production Upload

## Overview

This notebook:

* Loads the cleaned Bouldering Spots dataset (`bouldering_spots_final.csv`)
* Prepares the final schema for the production database
* Creates the `bouldering_spots` table in the production database
* Inserts all cleaned records into the table
* Validates the following constraints:
    * Row count
    * Duplicate ID checks
    * Foreign key validation
    * Coordinates validation

The goal of this notebook is to ensure that the bouldering dataset is fully ready for downstream usage in the Layered Data Pool.

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

## Loading the Dataset

In [2]:
df_final = pd.read_csv('bouldering_spots_final.csv')
df_final.head()

,id,district_id,neighborhood_id,name,latitude,longitude,geometry,neighborhood,district,is_indoor,...,street,house_number,postal_code,pricing,accessibility,opening_hours,phone,email,website,data_source
0,1066131768,11006006,604,Boulderfelsen,52.413943,13.264761,POINT (13.264761 52.413943),Zehlendorf,Steglitz-Zehlendorf,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OSM
1,1768495247,11002002,202,unknown_bouldering,52.495993,13.448546,POINT (13.448546 52.495993),Kreuzberg,Friedrichshain-Kreuzberg,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OSM
2,3966842994,11002002,202,Boulderklub Kreuzberg,52.495130,13.428675,POINT (13.428675 52.49513),Kreuzberg,Friedrichshain-Kreuzberg,True,...,Ohlauer Straße,38,10999.0,NaN,Not wheelchair accessible,Mo-Fr 07:00-22:00; Sa-Su 09:00-22:00,+49 30 51302181,NaN,http://boulderklubkreuzberg.de,OSM
3,3989801753,11005005,502,Cliffhanger,52.542111,13.221067,POINT (13.221067 52.542111),Haselhorst,Spandau,True,...,Zitadellenweg,NaN,13599.0,Entry Fee,NaN,Mo-Fr 10:00-22:00; Sa-Su 10:00-21:00,+49 30 67060160,NaN,https://cliffhanger-berlin.de/,OSM
4,4622626832,11008008,801,Kinderwald,52.479437,13.451600,POINT (13.451601 52.479437),Neukölln,Neukölln,True,...,NaN,NaN,NaN,Entry Fee,NaN,NaN,NaN,NaN,NaN,OSM

## Fixing Foreign Keys

Some of the ID fields such as `district_id` and `neighborhood_id` contain leading zeros
(e.g., `0407`, `0105`).

When reading CSV files, pandas may interpret these columns as integers, which would
automatically strip the leading zeros (e.g., `0407` → `407`).

To avoid this issue, these columns are converted to string.
After loading, the formatting of the IDs is normalized using `zfill()`:

- `neighborhood_id` → always 4 digits
- `district_id` → always 8 digits

This ensures consistency before inserting the data into the development database and
prevents data loss caused by unintended type conversion.

In [3]:
df_final['neighborhood_id'] = df_final['neighborhood_id'].astype('string').str.zfill(4)
df_final['district_id'] = df_final['district_id'].astype('string').str.zfill(8)
df_final[['neighborhood_id', 'district_id']].head()

  neighborhood_id district_id
0            0604    11006006
1            0202    11002002
2            0202    11002002
3            0502    11005005
4            0801    11008008

## Prepare Table Schema

The schema below defines the final table schema for the production database, based on the mandatory POI schema.

In [4]:
create_table_sql = """
DROP TABLE IF EXISTS berlin_source_data.bouldering_spots CASCADE;

CREATE TABLE berlin_source_data.bouldering_spots (
    id VARCHAR(20) PRIMARY KEY,
    district_id VARCHAR(20) NOT NULL,
    neighborhood_id VARCHAR(20),
    name VARCHAR(200) NOT NULL DEFAULT 'unknown_bouldering',
    latitude DECIMAL(9,6),
    longitude DECIMAL(9,6),
    geometry VARCHAR,
    neighborhood VARCHAR(100),
    district VARCHAR(100),
    is_indoor BOOLEAN,
    is_outdoor BOOLEAN,
    address VARCHAR(500),
    street VARCHAR(200),
    house_number VARCHAR(20),
    postal_code VARCHAR(20),
    pricing VARCHAR(20),
    accessibility VARCHAR(50),
    opening_hours VARCHAR(255),
    phone VARCHAR(100),
    email VARCHAR(255),
    website VARCHAR(255),
    data_source VARCHAR(20),
    CONSTRAINT fk_bouldering_district
        FOREIGN KEY (district_id)
        REFERENCES berlin_source_data.districts(district_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);
"""

## Create the Table

In [ ]:
engine = create_engine("postgresql+psycopg2://user_name:mQ2xW7zLpassword@localhost:5433/layereddb")

with engine.connect() as conn:
    conn.execute(text(create_table_sql))
    conn.commit()

print("Table bouldering_spots created successfully.")

Table bouldering_spots created successfully.

## Insert Data into Table

Insertion is performed with `if_exists="append"` to ensure repeatability during development.

In [6]:
df_final.to_sql(
    'bouldering_spots',
    engine,
    schema='berlin_source_data',
    if_exists='append',
    index=False
)

36

## Validate Constraints

### Row Count

This checks if the number of rows in the table matches the number of rows in the cleaned dataset.

In [7]:
print(f"The cleaned dataset has -->{df_final.shape[0]}<-- rows.")

with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM berlin_source_data.bouldering_spots"))
    print(f"The production table has -->{result.scalar()}<-- rows.")

The cleaned dataset has -->36<-- rows.
The production table has -->36<-- rows.

### Duplicate ID Checks

Ensures `id` is unique across all rows.
This is required for primary key consistency and downstream joins.

This should normally not be an issue due to OSM id's being unique and the `PRIMARY KEY` constraint.

In [8]:
with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT id, COUNT(*)
        FROM berlin_source_data.bouldering_spots
        GROUP BY id
        HAVING COUNT(*) > 1;
    """))
    duplicates = result.fetchall()
    print("Duplicate ID rows:", duplicates)

Duplicate ID rows: []

### Foreign Key Validation

Ensures every `district_id` exists in the `districts` reference table, and every `neighborhood_id` exists in the `neighborhoods` reference table.
This confirms referential integrity.

In [9]:
with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT b.district_id
        FROM berlin_source_data.bouldering_spots b
        LEFT JOIN berlin_source_data.districts d
        ON b.district_id = d.district_id
        WHERE d.district_id IS NULL;
    """))
    missing = result.fetchall()
    print("Invalid district_id rows:", missing)

Invalid district_id rows: []

In [10]:
with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT b.neighborhood_id
        FROM berlin_source_data.bouldering_spots b
        LEFT JOIN berlin_source_data.neighborhoods n
        ON b.neighborhood_id = n.neighborhood_id
        WHERE n.neighborhood_id IS NULL;
    """))
    missing = result.fetchall()
    print("Invalid neighborhood_id rows:", missing)

Invalid neighborhood_id rows: []

### Coordinates Validation

Ensures `latitude` and `longitude` are within the valid range for Berlin, and coordinates are within Berlin boundaries using PostGIS.

In [11]:
with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT *
        FROM berlin_source_data.bouldering_spots
        WHERE latitude < 52.3 OR latitude > 52.7
        OR longitude < 13.0 OR longitude > 13.8;
    """))
    missing = result.fetchall()
    print("Invalid coordinate rows:", missing)

Invalid coordinate rows: []

In [12]:
with engine.connect() as conn:
    result = conn.execute(text("""
        SELECT b.id,
               b.latitude,
               b.longitude,
               ST_SetSRID(ST_MakePoint(b.longitude, b.latitude), 4326) as geom
        FROM berlin_source_data.bouldering_spots b
        WHERE NOT EXISTS (
            SELECT 1
            FROM berlin_source_data.districts d
            -- Check if this point is inside the district's boundary polygon
            WHERE ST_Contains(d.geometry, ST_SetSRID(ST_MakePoint(b.longitude, b.latitude), 4326))
        );
    """))
    missing = result.fetchall()
    print("Invalid coordinate rows:", missing)

Invalid coordinate rows: []