In [1]:
pip install osmnx

Requirement already satisfied: osmnx in /opt/anaconda3/lib/python3.12/site-packages (2.1.0)
Requirement already satisfied: geopandas>=1.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from osmnx) (1.1.3)
Requirement already satisfied: networkx>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from osmnx) (3.3)
Requirement already satisfied: numpy>=1.24 in /opt/anaconda3/lib/python3.12/site-packages (from osmnx) (1.26.4)
Requirement already satisfied: pandas>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from osmnx) (2.2.2)
Requirement already satisfied: requests>=2.30 in /opt/anaconda3/lib/python3.12/site-packages (from osmnx) (2.32.3)
Requirement already satisfied: shapely>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from osmnx) (2.1.2)
Requirement already satisfied: pyogrio>=0.7.2 in /opt/anaconda3/lib/python3.12/site-packages (from geopandas>=1.0.1->osmnx) (0.12.1)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from geopandas>=1.0.1->osmnx) (24.1)
Requirement already satisfied: pyproj>=3.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from geopandas>=1.0.1->osmnx) (3.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.5->osmnx) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.5->osmnx) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.5->osmnx) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.30->osmnx) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.30->osmnx) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.30->osmnx) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.30->osmnx) (2025.1.31)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.5->osmnx) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import osmnx as ox
import pandas as pd
import geopandas as gpd
import re

##using osmnx to get example table with post_office

place_name = "Berlin, Germany"
tags = {"amenity": "post_office"}

# This works in OSMnx 2.x
gdf = ox.features_from_place(place_name, tags)

In [5]:
gdf.head()

                                    geometry addr:city addr:housenumber  \
element id
node    64888570   POINT (13.50718 52.56468)    Berlin                1
        89274887    POINT (13.41155 52.5197)       NaN              NaN
        97877441   POINT (13.49382 52.63579)    Berlin               21
        251290430  POINT (13.68899 52.44135)       NaN              NaN
        257705263  POINT (13.19801 52.53381)       NaN              NaN

                  addr:postcode     addr:street      amenity          brand  \
element id
node    64888570          13051  Prerower Platz  post_office  Deutsche Post
        89274887            NaN             NaN  post_office  Deutsche Post
        97877441          13125  Wiltbergstraße  post_office            NaN
        251290430           NaN             NaN  post_office            NaN
        257705263           NaN             NaN  post_office            NaN

                  brand:wikidata   brand:wikipedia level  ...  \
element id                                                ...
node    64888570         Q157645  en:Deutsche Post     0  ...
        89274887         Q157645  en:Deutsche Post     0  ...
        97877441             NaN               NaN   NaN  ...
        251290430            NaN               NaN   NaN  ...
        257705263            NaN               NaN     1  ...

                  payment:credit_cards payment:debit_cards addr:unit  \
element id
node    64888570                   NaN                 NaN       NaN
        89274887                   NaN                 NaN       NaN
        97877441                   NaN                 NaN       NaN
        251290430                  NaN                 NaN       NaN
        257705263                  NaN                 NaN       NaN

                  post_office:collection_times building building:levels  \
element id
node    64888570                           NaN      NaN             NaN
        89274887                           NaN      NaN             NaN
        97877441                           NaN      NaN             NaN
        251290430                          NaN      NaN             NaN
        257705263                          NaN      NaN             NaN

                  roof:levels roof:shape service:copy service:print
element id
node    64888570          NaN        NaN          NaN           NaN
        89274887          NaN        NaN          NaN           NaN
        97877441          NaN        NaN          NaN           NaN
        251290430         NaN        NaN          NaN           NaN
        257705263         NaN        NaN          NaN           NaN

[5 rows x 75 columns]

In [6]:
##using osmnx to get example table with parcel_locker

place_name = "Berlin, Germany"
tags = {"amenity": "parcel_locker"}

# This works in OSMnx 2.x
gdf_lock = ox.features_from_place(place_name, tags)
gdf_lock.head()

                                    geometry        amenity app_operated  \
element id
node    277707690  POINT (13.30243 52.49413)  parcel_locker           no
        281679672  POINT (13.46373 52.54582)  parcel_locker          NaN
        318581528  POINT (13.33275 52.50822)  parcel_locker          NaN
        322078518   POINT (13.36065 52.5453)  parcel_locker          NaN
        332136568  POINT (13.48605 52.46443)  parcel_locker          NaN

                  authentication:barcode_scanner authentication:bluetooth  \
element id
node    277707690                            yes                       no
        281679672                            NaN                      NaN
        318581528                            NaN                      NaN
        322078518                            NaN                      NaN
        332136568                            yes                      NaN

                         branch            brand brand:wikidata  \
element id
node    277707690           143  DHL Packstation       Q1766703
        281679672           NaN  DHL Packstation       Q1766703
        318581528  Paketstation  DHL Packstation       Q1766703
        322078518           NaN  DHL Packstation       Q1766703
        332136568           NaN  DHL Packstation       Q1766703

                  brand:wikipedia  check_date  ... payment:credit_cards  \
element id                                     ...
node    277707690  de:Packstation  2025-04-07  ...                  NaN
        281679672  de:Packstation         NaN  ...                  NaN
        318581528  de:Packstation  2024-05-23  ...                  NaN
        322078518  de:Packstation  2024-11-29  ...                  NaN
        332136568  de:Packstation  2025-02-20  ...                  NaN

                  payment:mastercard payment:v_pay payment:visa short_name  \
element id
node    277707690                NaN           NaN          NaN        NaN
        281679672                NaN           NaN          NaN        NaN
        318581528                NaN           NaN          NaN        NaN
        322078518                NaN           NaN          NaN        NaN
        332136568                NaN           NaN          NaN        NaN

                  authentication:app addr:country addr:suburb  \
element id
node    277707690                NaN          NaN         NaN
        281679672                NaN          NaN         NaN
        318581528                NaN          NaN         NaN
        322078518                NaN          NaN         NaN
        332136568                NaN          NaN         NaN

                  brand:wikipedia:ar construction_date
element id
node    277707690                NaN               NaN
        281679672                NaN               NaN
        318581528                NaN               NaN
        322078518                NaN               NaN
        332136568                NaN               NaN

[5 rows x 92 columns]

In [7]:
# Making 'id' index into 'id' column
gdf_lock = gdf_lock.reset_index()
gdf = gdf.reset_index()

In [8]:
gdf_lock.head(2)

,element,id,geometry,amenity,app_operated,authentication:barcode_scanner,authentication:bluetooth,branch,brand,brand:wikidata,...,payment:credit_cards,payment:mastercard,payment:v_pay,payment:visa,short_name,authentication:app,addr:country,addr:suburb,brand:wikipedia:ar,construction_date
0,node,277707690,POINT (13.30243 52.49413),parcel_locker,no,yes,no,143,DHL Packstation,Q1766703,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,node,281679672,POINT (13.46373 52.54582),parcel_locker,NaN,NaN,NaN,NaN,DHL Packstation,Q1766703,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
gdf.shape

(208, 77)

In [10]:
gdf_lock.shape

(781, 94)

In [135]:
# For gdf
# Couting percentage of non-null values in each column

# calculate non-null
count_filled = gdf.notnull().sum()

# Calculate filled data
percent_filled = (gdf.notnull().mean() * 100).round(2)

# Calculate missing (NaN)
percent_missing = (gdf.isnull().mean() * 100).round(2)

# Combine into a DataFrame
df_audit = pd.DataFrame({
    'Filled_Count': count_filled,
    'Filled_%': percent_filled,
    'Missing_%': percent_missing
})

# Sort by percentage of filled data
df_audit = df_audit.sort_values(by='Filled_%', ascending=False)

# To show everything in the DataFrame without truncation
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_audit)

                              Filled_Count  Filled_%  Missing_%
element                                208    100.00       0.00
amenity                                208    100.00       0.00
geometry                               208    100.00       0.00
id                                     208    100.00       0.00
name                                   171     82.21      17.79
opening_hours                          142     68.27      31.73
wheelchair                             116     55.77      44.23
operator                               108     51.92      48.08
addr:street                             89     42.79      57.21
operator:wikidata                       87     41.83      58.17
addr:housenumber                        85     40.87      59.13
addr:postcode                           80     38.46      61.54
addr:city                               74     35.58      64.42
brand                                   73     35.10      64.90
brand:wikidata                          58     27.88      72.12
operator:wikipedia                      43     20.67      79.33
addr:suburb                             36     17.31      82.69
addr:country                            34     16.35      83.65
check_date:opening_hours                34     16.35      83.65
brand:wikipedia                         33     15.87      84.13
check_date                              23     11.06      88.94
post_office:type                        22     10.58      89.42
shop                                    21     10.10      89.90
level                                   21     10.10      89.90
ref                                     12      5.77      94.23
post_office:brand                       11      5.29      94.71
website                                 11      5.29      94.71
phone                                   10      4.81      95.19
post_office:service_provider             9      4.33      95.67
description                              8      3.85      96.15
post_office                              8      3.85      96.15
note                                     5      2.40      97.60
operator:type                            4      1.92      98.08
lottery                                  4      1.92      98.08
source                                   4      1.92      98.08
toilets:wheelchair                       4      1.92      98.08
branch                                   3      1.44      98.56
atm                                      3      1.44      98.56
contact:phone                            3      1.44      98.56
opening_hours:signed                     3      1.44      98.56
wheelchair:description                   3      1.44      98.56
noname                                   2      0.96      99.04
payment:cash                             2      0.96      99.04
name:signed                              2      0.96      99.04
surveillance                             2      0.96      99.04
building                                 1      0.48      99.52
post_office:collection_times             1      0.48      99.52
addr:unit                                1      0.48      99.52
ref:vatin                                1      0.48      99.52
building:levels                          1      0.48      99.52
payment:credit_cards                     1      0.48      99.52
internet_access                          1      0.48      99.52
post_office:parcel_pickup                1      0.48      99.52
post_office:parcel_from                  1      0.48      99.52
post_office:letter_from                  1      0.48      99.52
roof:levels                              1      0.48      99.52
disused:shop                             1      0.48      99.52
roof:shape                               1      0.48      99.52
service:copy                             1      0.48      99.52
payment:debit_cards                      1      0.48      99.52
drink:coffee                             1      0.48      99.52
email                                    1      0.48      99.52
outdoor_seating                          1      0.48      99.52
name:de                                  1      0.48      99.52
payment:cards                            1      0.48      99.52
addr:place                               1      0.48      99.52
addr:floor                               1      0.48      99.52
access:covid19                           1      0.48      99.52
entrance                                 1      0.48      99.52
collection_times                         1      0.48      99.52
postal_code                              1      0.48      99.52
type                                     1      0.48      99.52
last_checked                             1      0.48      99.52
name:zh                                  1      0.48      99.52
wheelchair:description:de                1      0.48      99.52
drink:club-mate                          1      0.48      99.52
service:print                            1      0.48      99.52

In [136]:
# For gdf_lock
# Couting percentage of non-null values in each column

# calculate non-null
count_filled = gdf_lock.notnull().sum()

# Calculate filled data
percent_filled = (gdf_lock.notnull().mean() * 100).round(2)

# Calculate missing (NaN)
percent_missing = (gdf_lock.isnull().mean() * 100).round(2)

# Combine into a DataFrame
df_audit = pd.DataFrame({
    'Filled_Count': count_filled,
    'Filled_%': percent_filled,
    'Missing_%': percent_missing
})

# Sort by percentage of filled data
df_audit = df_audit.sort_values(by='Filled_%', ascending=False)

# To show everything in the DataFrame without truncation
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_audit)

                                Filled_Count  Filled_%  Missing_%
element                                  781    100.00       0.00
geometry                                 781    100.00       0.00
amenity                                  781    100.00       0.00
id                                       781    100.00       0.00
brand                                    749     95.90       4.10
brand:wikidata                           737     94.37       5.63
operator                                 663     84.89      15.11
parcel_mail_in                           623     79.77      20.23
parcel_pickup                            585     74.90      25.10
ref                                      565     72.34      27.66
operator:wikidata                        519     66.45      33.55
parcel_locker:type                       377     48.27      51.73
brand:wikipedia                          328     42.00      58.00
check_date                               318     40.72      59.28
operator:wikipedia                       316     40.46      59.54
postal_code                              311     39.82      60.18
opening_hours                            308     39.44      60.56
wheelchair                               158     20.23      79.77
name                                     128     16.39      83.61
surveillance                             119     15.24      84.76
display_operated                          87     11.14      88.86
indoor                                    79     10.12      89.88
authentication:barcode_scanner            77      9.86      90.14
colour                                    59      7.55      92.45
level                                     44      5.63      94.37
covered                                   40      5.12      94.88
object:street                             38      4.87      95.13
object:housenumber                        37      4.74      95.26
app_operated                              30      3.84      96.16
source                                    29      3.71      96.29
object:postcode                           20      2.56      97.44
website                                   17      2.18      97.82
addr:housenumber                          15      1.92      98.08
addr:postcode                             15      1.92      98.08
description                               15      1.92      98.08
addr:street                               15      1.92      98.08
addr:floor                                12      1.54      98.46
note                                      12      1.54      98.46
authentication:bluetooth                  12      1.54      98.46
object:floor                              11      1.41      98.59
object:city                               10      1.28      98.72
display                                   10      1.28      98.72
contact:website                            9      1.15      98.85
object:country                             8      1.02      98.98
addr:city                                  6      0.77      99.23
label_printer                              6      0.77      99.23
material                                   6      0.77      99.23
lit                                        5      0.64      99.36
mapillary                                  4      0.51      99.49
branch                                     4      0.51      99.49
payment:account_cards                      4      0.51      99.49
capacity                                   3      0.38      99.62
packstation_type                           3      0.38      99.62
image                                      3      0.38      99.62
not:brand:wikidata                         3      0.38      99.62
addr:suburb                                2      0.26      99.74
addr:country                               2      0.26      99.74
short_name                                 2      0.26      99.74
payment:cards                              2      0.26      99.74
direction                                  2      0.26      99.74
payment:app                                2      0.26      99.74
mobile_phone                               2      0.26      99.74
start_date                                 2      0.26      99.74
payment:none                               2      0.26      99.74
object:suburb                              2      0.26      99.74
payment:debit_cards                        2      0.26      99.74
name:ja                                    2      0.26      99.74
access                                     2      0.26      99.74
collection_times                           2      0.26      99.74
operator:type                              2      0.26      99.74
note:de                                    2      0.26      99.74
brand:wikipedia:ar                         1      0.13      99.87
description:en                             1      0.13      99.87
authentication:app                         1      0.13      99.87
toilets:wheelchair                         1      0.13      99.87
payment:visa                               1      0.13      99.87
payment:v_pay                              1      0.13      99.87
payment:mastercard                         1      0.13      99.87
payment:credit_cards                       1      0.13      99.87
payment:contactless                        1      0.13      99.87
layer                                      1      0.13      99.87
surveillance:type                          1      0.13      99.87
surface                                    1      0.13      99.87
contact:phone                              1      0.13      99.87
contact:email                              1      0.13      99.87
camera:type                                1      0.13      99.87
description:de                             1      0.13      99.87
atm                                        1      0.13      99.87
payment:girocard                           1      0.13      99.87
refrigerated                               1      0.13      99.87
fixme                                      1      0.13      99.87
rev                                        1      0.13      99.87
last_checked                               1      0.13      99.87
construction_date                          1      0.13      99.87

## **Concatenate gdf and gdf_lock**

In [137]:
def prepare_gdf_clean(df):
    # Reset index so 'id' becomes column
    temp = df.reset_index().copy()
    
    # Take the center for latitude & longitude (some of them cause error bcs they are not a point, but a polygon/building)
    temp['latitude'] = df.geometry.centroid.y
    temp['longitude'] = df.geometry.centroid.x
    
    return temp

In [138]:
df_post_clean = prepare_gdf_clean(gdf)
df_lock_clean = prepare_gdf_clean(gdf_lock)

/var/folders/8x/d1r34xq1421f9fbxznf2_79r0000gn/T/ipykernel_2756/2730627299.py:6: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  temp['latitude'] = df.geometry.centroid.y
/var/folders/8x/d1r34xq1421f9fbxznf2_79r0000gn/T/ipykernel_2756/2730627299.py:7: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  temp['longitude'] = df.geometry.centroid.x
/var/folders/8x/d1r34xq1421f9fbxznf2_79r0000gn/T/ipykernel_2756/2730627299.py:6: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  temp['latitude'] = df.geometry.centroid.y
/var/folders/8x/d1r34xq1421f9fbxznf2_79r0000gn/T/ipykernel_2756/2730627299.py:7: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  temp['longitude'] = df.geometry.centroid.x

In [139]:
gdf.head(2)

,element,id,geometry,addr:city,addr:housenumber,addr:postcode,addr:street,amenity,brand,brand:wikidata,...,payment:credit_cards,payment:debit_cards,addr:unit,post_office:collection_times,building,building:levels,roof:levels,roof:shape,service:copy,service:print
0,node,64888570,POINT (13.50718 52.56468),Berlin,1,13051,Prerower Platz,post_office,Deutsche Post,Q157645,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,node,89274887,POINT (13.41155 52.5197),NaN,NaN,NaN,NaN,post_office,Deutsche Post,Q157645,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [140]:
gdf_lock.head(2)

,element,id,geometry,amenity,app_operated,authentication:barcode_scanner,authentication:bluetooth,branch,brand,brand:wikidata,...,payment:credit_cards,payment:mastercard,payment:v_pay,payment:visa,short_name,authentication:app,addr:country,addr:suburb,brand:wikipedia:ar,construction_date
0,node,277707690,POINT (13.30243 52.49413),parcel_locker,no,yes,no,143,DHL Packstation,Q1766703,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,node,281679672,POINT (13.46373 52.54582),parcel_locker,NaN,NaN,NaN,NaN,DHL Packstation,Q1766703,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
# Concatenate
df_all = pd.concat([df_post_clean, df_lock_clean], ignore_index=True)

# drop duplicates , 593 data are dropped
df_all = df_all.drop_duplicates(subset=['id'], keep='first')

In [149]:
# Columns I keep from both
target_columns = [
    'id', 
    'name',
    'ref', 
    'shop',
    'amenity', 
    'operator', 
    'brand', 
    'addr:street',
    'addr:housenumber',
    'addr:postcode',
    'level',
    'wheelchair',
    'service:copy',
    'service:print',
    'app_operated',
    'authentication:barcode_scanner',
    'authentication:bluetooth',
    'display_operated',
    'label_printer',
    'parcel_locker:type',
    'parcel_mail_in',
    'parcel_pickup',
    'level',
    'note',
    'note:de',
    'description',
    'geometry', 
    'latitude', 
    'longitude', 
    'opening_hours', 
    'website',
    'source',
    'last_checked'
]

available_cols = [c for c in target_columns if c in df_all.columns]
df_final = df_all[available_cols].copy()

# add data source and last_updated
df_final['data_source'] = 'OpenStreetMap'

print(f"Total row: {len(df_final)}")
df_final.head()

Total row: 989

,id,name,ref,shop,amenity,operator,brand,addr:street,addr:housenumber,addr:postcode,...,note:de,description,geometry,latitude,longitude,opening_hours,website,source,last_checked,data_source
0,64888570,Deutsche Post,NaN,NaN,post_office,Deutsche Post,Deutsche Post,Prerower Platz,1,13051,...,NaN,NaN,POINT (13.50718 52.56468),52.564677,13.507182,Mo-Fr 09:00-18:30; Sa 09:00-12:00,NaN,NaN,NaN,OpenStreetMap
1,89274887,Deutsche Post,NaN,NaN,post_office,Deutsche Post,Deutsche Post,NaN,NaN,NaN,...,NaN,NaN,POINT (13.41155 52.5197),52.519698,13.411554,Mo-Fr 09:00-19:00; Sa 09:00-15:00,NaN,NaN,NaN,OpenStreetMap
2,97877441,Postbank Finanzcenter,NaN,NaN,post_office,NaN,NaN,Wiltbergstraße,21,13125,...,NaN,NaN,POINT (13.49382 52.63579),52.635785,13.493816,"PH,Mo-Su 00:00-24:00",NaN,NaN,NaN,OpenStreetMap
3,251290430,NaN,NaN,NaN,post_office,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,POINT (13.68899 52.44135),52.441346,13.688988,NaN,NaN,NaN,NaN,OpenStreetMap
4,257705263,Postbank Finanzcenter,NaN,NaN,post_office,Postbank;Deutsche Post;DHL,NaN,NaN,NaN,NaN,...,NaN,NaN,POINT (13.19801 52.53381),52.533808,13.198011,"Mo-Fr 09:30-18:00; Sa 09:30-17:30; Su,PH off",NaN,NaN,NaN,OpenStreetMap

In [150]:
# checking unique name in 'name'

df_final['name'].unique()

array(['Deutsche Post', 'Postbank Finanzcenter', nan, 'Post',
       'Postbank Filiale 506', 'Postbank', 'Schmökerzeit', 'Postfiliale',
       'pin MAIL', 'k kiosk', 'Zeitungsladen Parlak', 'Kiosk',
       'Post-Shop', 'Hermes Shop', 'tabaCCenter', 'DHL',
       'Deutsche Post / Postbank', 'StoExpress Germany GmbH',
       'Deutsche Post Partnerfiliale', 'Poststelle', "Moni's Postshop",
       'Zok Regattahandel', 'Zeitungen & Tabakwaren Barth', 'PIN Mail AG',
       'kkiosk', 'Hermes', 'Spätkauf Post', 'DHL BVG Kiosk',
       'P&P Bürobedarf', 'UPS Paketshop', 'Lotto Post Tabak',
       'Post-Agentur', 'Postbank Filialcenter',
       'Postcon Konsolidierungs GmbH', 'Getränke Hoffmann',
       'Post office and newspaper shop', 'Post & DHL',
       'Postfiliale Haselhorst', 'Post-Point',
       'Postfiliale am Falkenplatz', 'Uni-Shop', 'Pens & Scissors',
       'DPD Store Friedrichshain', 'Lotto Post', 'Hermes Paketshop',
       'DHL Paketshop', 'DHL Postfiliale 512', 'UPS Access Point',
       'Späti', 'ATM EXTRAS', 'PIN AG - Depot Wilmersdorf',
       'Lotto/Tabak/Presse Raschel', 'Deutsche Post - DHL Hagenplatz',
       'GSL Paketshop', 'MMD Paketshop', 'Deutsche Post Filiale 501',
       'Hermes PaketShop', 'Pin Mail', 'Pen & Paper', 'DHL Paketshop 444',
       'Filiale 413', 'Bärlin Company', 'The Winsy Späti',
       'Lotto-Tabak-Presse Türkmann', 'Paketshop 651', 'Nova Post',
       'Deutsche Post Filiale 536', 'Speditionsshop Steglitz',
       'Kaiser Wilhelm Str 60-62, 12247', 'Postfiliale 442', 'DPD',
       'DHL Postfiliale 543', 'Postfiliale 404', 'Mail Boxes Etc.',
       'GLS PaketShop', 'Deutsche Post Filiale 535', 'DHL im Bäcker Pera',
       'Kiosk 39', 'Späti 48', 'dies & das',
       'Thats so Berlin - Postagentur und Tabakshop',
       'Postshop Prenzlauer Berg', 'Copy & More', 'DPD Pickup Shop',
       'DPD PickupShop', 'DHL PaketShop', 'Deutsche Post Filiale 537',
       'Packstation 195', 'DHL Packstation 131', 'DHL Packstation 433',
       'DHL-Station 237', 'DHL-Station 283', 'Amazon Hub Locker',
       'DHL Packstation 446', 'Packstation 418', 'DHL Packstation 184',
       'DHL Packstation 219', 'DHL Packstation 663', 'DHL Paketbox',
       'amazonlocker', 'Packstation 123', 'Amazon Hub Locker Dagame',
       'Packstation 611', 'DHL Packstation 141', 'Packstation 453',
       'Packstation 576', 'baldassarre', 'DHL Packstation 687', 'marcus',
       'Amazon Locker - caelab', 'Amazon Hub Locker – kline',
       'Amazon Locker - kerrie', 'Amazon Locker - caelan',
       'MyLocker24 Box 225', 'DHL Packstation 129', 'gene',
       'Packstation 284', 'enrike', 'Amazon Locker: dalcio',
       'Packstation 258', 'DHL Packstation 143', '397',
       'Amazon Locker padme', 'DHL Packstation 689',
       'Amazon Locker zella', '248', 'Packstation 218', 'Jasmin',
       'Poststation 705', 'Packstation 143', 'gennaro',
       'Amazon Locker - xyleigh', 'DHL Packstation 125',
       'Packstation 529', 'Amazon Locker lava', 'grischa',
       'DHL Packstation', 'Amazon Locker', 'Packstation',
       'Packstation 255', 'Packstation 407', 'DHL Packstation 534',
       'myflexbox', 'Kirsten', 'Andryala', 'DHL Paketbox 276',
       'Packstation 238', 'Amazon Locker austernpilz', 'Packstation 254',
       'DHL Packstation 412', 'Amazon Locker: abeerah',
       'DPD/FedEx/GLS/UPS', 'IKEA Abholbox', 'DHL Paketbox 238'],
      dtype=object)

In [151]:
def clean_row_advanced(row):
    name = str(row['name']).lower() if pd.notna(row['name']) else "" # Isi variabel name dengan versi kecil (lower), JIKA datanya ada, kalau tidak ada ya kasih teks kosong
    current_ref = str(row['ref']) if pd.notna(row['ref']) else "" # kalau baris, kolom ref ada isinya, maka jadikan string, kalau tidak ada maka teks kosong
    
    # Move numbers in 'name' to 'ref'
    # cari angka >= 3 digit
    found_numbers = re.findall(r'\d{3,}', name) # result becomes list
    # kalau ketemu (dari found_number) DAN kolom current_ref kosong
    if found_numbers and not current_ref:
        row['ref'] = found_numbers[0] # dari list ['123','729',...]
        # raw string, digit 0-9, minimum 3x sequentially or more
        name = re.sub(r'\d{3,}', '', name).strip() # Cari pola angka (>= 3 digit), lalu GANTI (substitute) dengan '' (teks kosong/dihapus) dan STRIP (hapus) spasi (dari Packstation 123 -> Packstation)

    # 2. Mapping 'name'
    if any(x in name for x in ["deutsche post", "postfiliale", "post office"]):
        row['brand_clean'] = "Deutsche Post"
    elif "postbank" in name:
        row['brand_clean'] = "Postbank" 
    elif any(x in name for x in ["dhl", "packstation", "paketbox", "paketshop"]):
        row['brand_clean'] = "DHL"
    elif any(x in name for x in ["amazon", "amazon hub", "amazon locker"]):
        row['brand_clean'] = "Amazon"
    elif "hermes" in name:
        row['brand_clean'] = "Hermes"
    elif "gls" in name:
        row['brand_clean'] = "GLS"
    elif "dpd" in name:
        row['brand_clean'] = "DPD"
    elif "ups" in name:
        row['brand_clean'] = "UPS"
    elif "fedex" in name:
        row['brand_clean'] = "FedEx"
    elif "myflexbox" in name:
        row['brand_clean'] = "MyFlexbox"
    elif any(x in name for x in ["pin mail", "pin ag"]):
        row['brand_clean'] = "PIN Mail"
    elif any(x in name for x in ["kiosk", "späti", "lotto", "tabak", "zeitschrift", "k kiosk"]):
        row['brand_clean'] = "Kiosk"
    else:
        # for others that has unusual shop name
        row['brand_clean'] = "Independent Retailer"
        
    return row

# Eksekusi
df_final = df_final.apply(clean_row_advanced, axis=1)

In [152]:
df_final.head()

,id,name,ref,shop,amenity,operator,brand,addr:street,addr:housenumber,addr:postcode,...,description,geometry,latitude,longitude,opening_hours,website,source,last_checked,data_source,brand_clean
0,64888570,Deutsche Post,NaN,NaN,post_office,Deutsche Post,Deutsche Post,Prerower Platz,1,13051,...,NaN,POINT (13.50718 52.56468),52.564677,13.507182,Mo-Fr 09:00-18:30; Sa 09:00-12:00,NaN,NaN,NaN,OpenStreetMap,Deutsche Post
1,89274887,Deutsche Post,NaN,NaN,post_office,Deutsche Post,Deutsche Post,NaN,NaN,NaN,...,NaN,POINT (13.41155 52.5197),52.519698,13.411554,Mo-Fr 09:00-19:00; Sa 09:00-15:00,NaN,NaN,NaN,OpenStreetMap,Deutsche Post
2,97877441,Postbank Finanzcenter,NaN,NaN,post_office,NaN,NaN,Wiltbergstraße,21,13125,...,NaN,POINT (13.49382 52.63579),52.635785,13.493816,"PH,Mo-Su 00:00-24:00",NaN,NaN,NaN,OpenStreetMap,Postbank
3,251290430,NaN,NaN,NaN,post_office,NaN,NaN,NaN,NaN,NaN,...,NaN,POINT (13.68899 52.44135),52.441346,13.688988,NaN,NaN,NaN,NaN,OpenStreetMap,Independent Retailer
4,257705263,Postbank Finanzcenter,NaN,NaN,post_office,Postbank;Deutsche Post;DHL,NaN,NaN,NaN,NaN,...,NaN,POINT (13.19801 52.53381),52.533808,13.198011,"Mo-Fr 09:30-18:00; Sa 09:30-17:30; Su,PH off",NaN,NaN,NaN,OpenStreetMap,Postbank

In [153]:
df_final.shape

(989, 35)

In [ ]:
# checking ref that is not numeric
# Pakai .fillna('') supaya yang NaN jadi teks kosong, jadi tidak bikin error 'float'
# non_numeric_ref = df_final[
#    (df_final['ref'].fillna('').str.isdigit() == False) & 
#    (df_final['ref'].notna())]

# print(f"Found {len(non_numeric_ref)} rows with NOT numeric refa")
# non_numeric_ref[['name', 'ref','brand','amenity','brand_clean']].head(20)

Found 103 rows with NOT numeric refa

,name,ref,brand,amenity,brand_clean
61,P&P Bürobedarf,Deutsche Post Filiale Berlin 211,NaN,post_office,Independent Retailer
307,NaN,julius,Amazon Hub,parcel_locker,Independent Retailer
313,Amazon Hub Locker,fabian,Amazon Hub,parcel_locker,Amazon
321,Amazon Hub Locker,romy,Amazon Hub,parcel_locker,Amazon
335,NaN,Isabell,Amazon Hub,parcel_locker,Independent Retailer
341,NaN,jannis,Amazon Hub,parcel_locker,Independent Retailer
377,NaN,revelle,Amazon Hub,parcel_locker,Independent Retailer
397,Amazon Hub Locker,Carolien,Amazon Hub,parcel_locker,Amazon
399,NaN,Mirja,Amazon Locker,parcel_locker,Independent Retailer
440,NaN,leena,Amazon,parcel_locker,Independent Retailer
441,NaN,jenna,Amazon Hub,parcel_locker,Independent Retailer
450,NaN,yoselin,Amazon Locker,parcel_locker,Independent Retailer
453,NaN,june,Amazon Locker,parcel_locker,Independent Retailer
455,NaN,filomena,Amazon Locker,parcel_locker,Independent Retailer
456,NaN,carissa,Amazon Locker,parcel_locker,Independent Retailer
460,NaN,bake,Amazon Locker,parcel_locker,Independent Retailer
462,NaN,alang,Amazon Locker,parcel_locker,Independent Retailer
466,Amazon Hub Locker,hair,Amazon Hub,parcel_locker,Amazon
467,NaN,dali,Amazon Hub,parcel_locker,Independent Retailer
485,Amazon Hub Locker,jann,Amazon Hub,parcel_locker,Amazon

In [157]:
# drop 'ref' and 'name' columns

cols_to_drop = ['name','ref']

df_final = df_final.drop(columns=[c for c in cols_to_drop if c in df_final.columns], errors='ignore')

In [158]:
df_final.head()

,id,brand_clean,shop,amenity,operator,brand,addr:street,addr:housenumber,addr:postcode,level,...,note:de,description,geometry,latitude,longitude,opening_hours,website,source,last_checked,data_source
0,64888570,Deutsche Post,NaN,post_office,Deutsche Post,Deutsche Post,Prerower Platz,1,13051,0,...,NaN,NaN,POINT (13.50718 52.56468),52.564677,13.507182,Mo-Fr 09:00-18:30; Sa 09:00-12:00,NaN,NaN,NaN,OpenStreetMap
1,89274887,Deutsche Post,NaN,post_office,Deutsche Post,Deutsche Post,NaN,NaN,NaN,0,...,NaN,NaN,POINT (13.41155 52.5197),52.519698,13.411554,Mo-Fr 09:00-19:00; Sa 09:00-15:00,NaN,NaN,NaN,OpenStreetMap
2,97877441,Postbank,NaN,post_office,NaN,NaN,Wiltbergstraße,21,13125,NaN,...,NaN,NaN,POINT (13.49382 52.63579),52.635785,13.493816,"PH,Mo-Su 00:00-24:00",NaN,NaN,NaN,OpenStreetMap
3,251290430,Independent Retailer,NaN,post_office,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,POINT (13.68899 52.44135),52.441346,13.688988,NaN,NaN,NaN,NaN,OpenStreetMap
4,257705263,Postbank,NaN,post_office,Postbank;Deutsche Post;DHL,NaN,NaN,NaN,NaN,1,...,NaN,NaN,POINT (13.19801 52.53381),52.533808,13.198011,"Mo-Fr 09:30-18:00; Sa 09:30-17:30; Su,PH off",NaN,NaN,NaN,OpenStreetMap

In [159]:
# moving 'brand_clean' to be next to 'id'
# by taking all of the columns and ...
all_columns = df_final.columns.tolist()

priority_cols = ['id','brand_clean']

other_cols = [c for c in all_columns if c not in priority_cols]

df_final = df_final[priority_cols + other_cols]

df_final.head()

,id,brand_clean,shop,amenity,operator,brand,addr:street,addr:housenumber,addr:postcode,level,...,note:de,description,geometry,latitude,longitude,opening_hours,website,source,last_checked,data_source
0,64888570,Deutsche Post,NaN,post_office,Deutsche Post,Deutsche Post,Prerower Platz,1,13051,0,...,NaN,NaN,POINT (13.50718 52.56468),52.564677,13.507182,Mo-Fr 09:00-18:30; Sa 09:00-12:00,NaN,NaN,NaN,OpenStreetMap
1,89274887,Deutsche Post,NaN,post_office,Deutsche Post,Deutsche Post,NaN,NaN,NaN,0,...,NaN,NaN,POINT (13.41155 52.5197),52.519698,13.411554,Mo-Fr 09:00-19:00; Sa 09:00-15:00,NaN,NaN,NaN,OpenStreetMap
2,97877441,Postbank,NaN,post_office,NaN,NaN,Wiltbergstraße,21,13125,NaN,...,NaN,NaN,POINT (13.49382 52.63579),52.635785,13.493816,"PH,Mo-Su 00:00-24:00",NaN,NaN,NaN,OpenStreetMap
3,251290430,Independent Retailer,NaN,post_office,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,POINT (13.68899 52.44135),52.441346,13.688988,NaN,NaN,NaN,NaN,OpenStreetMap
4,257705263,Postbank,NaN,post_office,Postbank;Deutsche Post;DHL,NaN,NaN,NaN,NaN,1,...,NaN,NaN,POINT (13.19801 52.53381),52.533808,13.198011,"Mo-Fr 09:30-18:00; Sa 09:30-17:30; Su,PH off",NaN,NaN,NaN,OpenStreetMap

other_cols = [c for c in all_columns if c not in priority_cols]

- all_columns: Ini adalah seluruh isi lemari kamu (semua nama kolom: id, name, ref, lat, long, geometry, dll).

- priority_cols: Ini adalah baju pesta kamu yang mau dipakai duluan (id, brand_clean).

- if c not in priority_cols: Ini filternya. Kamu bilang: "Eh, kalau nama kolom ini BUKAN baju pesta (id/brand_clean), berarti dia baju harian (kolom sisa). Masukin ke kantong other_cols!"

Hasilnya: other_cols sekarang berisi semua nama kolom KECUALI id dan brand_clean

In [161]:
df_final.shape

(989, 47)